#!/usr/bin/env python3
"""
TLD Scraper using Selenium
Usage: python3 get_tlds.py --input source.txt
"""

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.common.exceptions import WebDriverException, TimeoutException
import tldextract
import datetime
import time
import argparse
import sys
import os

def setup_driver():
    """Setup and configure Chrome driver"""
    chrome_options = Options()
    chrome_options.add_argument("--headless")  # Run in background
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("--disable-blink-features=AutomationControlled")
    chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
    chrome_options.add_experimental_option('useAutomationExtension', False)
    
    try:
        driver = webdriver.Chrome(options=chrome_options)
        driver.set_page_load_timeout(30)  # 30 seconds timeout
        return driver
    except Exception as e:
        print(f"Error setting up Chrome driver: {e}")
        print("Please ensure Chrome and ChromeDriver are installed and in your PATH")
        sys.exit(1)

def read_urls_from_file(filename):
    """Read URLs from input file, skipping comments and empty lines"""
    urls = []
    try:
        with open(filename, 'r', encoding='utf-8') as file:
            for line in file:
                line = line.strip()
                # Skip empty lines and comments
                if line and not line.startswith('#'):
                    urls.append(line)
        return urls
    except FileNotFoundError:
        print(f"Error: Input file '{filename}' not found.")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(1)

def extract_tld_from_url(url):
    """Extract TLD from a URL using tldextract"""
    try:
        extracted = tldextract.extract(url)
        # Combine domain and suffix (e.g., 'google.com')
        domain_parts = [extracted.domain, extracted.suffix]
        tld = '.'.join(part for part in domain_parts if part)
        return tld.lower() if tld else None
    except Exception as e:
        print(f"Error extracting TLD from {url}: {e}")
        return None

def scrape_urls_from_website(driver, url):
    """Scrape all URLs from a given website"""
    found_urls = set()
    
    try:
        print(f"Scraping: {url}")
        driver.get(url)
        time.sleep(2)  # Wait for page to load
        
        # Find all anchor tags with href attributes
        links = driver.find_elements(By.TAG_NAME, "a")
        
        for link in links:
            try:
                href = link.get_attribute("href")
                if href and href.startswith(('http://', 'https://')):
                    found_urls.add(href)
            except Exception as e:
                print(f"Error processing link: {e}")
                continue
                
    except TimeoutException:
        print(f"Timeout loading: {url}")
    except WebDriverException as e:
        print(f"Error accessing {url}: {e}")
    except Exception as e:
        print(f"Unexpected error with {url}: {e}")
    
    return found_urls

def ensure_directory_exists(filepath):
    """Ensure the directory for the file exists"""
    directory = os.path.dirname(filepath)
    if directory and not os.path.exists(directory):
        os.makedirs(directory, exist_ok=True)
        print(f"Created directory: {directory}")

def save_tlds_to_file(tlds, filename, input_file, total_urls_processed):
    """Save TLDs to a text file in Linux hosts format with custom header"""
    try:
        # Ensure the directory exists
        ensure_directory_exists(filename)
        
        with open(filename, 'w', encoding='utf-8') as file:
            # Write header information
            file.write("# Linux hosts file generated by TLD Scraper\n")
            file.write(f"# Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            file.write(f"# Input file: {input_file}\n")
            file.write(f"# URLs processed: {total_urls_processed}\n")
            file.write(f"# Unique TLDs found: {len(tlds)}\n")
            file.write("# \n")
            
            # Standard hosts file entries
            file.write("127.0.0.1 localhost\n")
            file.write("127.0.0.1 localhost.localdomain\n")
            file.write("127.0.0.1 local\n")
            file.write("255.255.255.255 broadcasthost\n")
            file.write("::1 localhost\n")
            file.write("::1 ip6-localhost\n")
            file.write("::1 ip6-loopback\n")
            file.write("fe80::1%lo0 localhost\n")
            file.write("ff00::0 ip6-localnet\n")
            file.write("ff00::0 ip6-mcastprefix\n")
            file.write("ff02::1 ip6-allnodes\n")
            file.write("ff02::2 ip6-allrouters\n")
            file.write("ff02::3 ip6-allhosts\n")
            file.write("0.0.0.0 0.0.0.0\n")
            file.write("\n")
            file.write("# Custom host records are listed here.\n")
            file.write("\n")
            file.write("\n")
            file.write("# End of custom host records.\n")
            file.write("\n")
            file.write("#=====================================\n")
            file.write("# Title: Hosts contributed by Mous B\n")
            file.write("#=====================================\n")
            file.write("\n")
            
            # Write TLDs in hosts file format using 0.0.0.0
            for tld in sorted(tlds):
                file.write(f"0.0.0.0 {tld}\n")
            
            file.write("\n# End of generated hosts file\n")
        
        print(f"Hosts file saved to: {filename}")
        return True
    except Exception as e:
        print(f"Error saving file: {e}")
        return False

def parse_arguments():
    """Parse command line arguments"""
    parser = argparse.ArgumentParser(description='Scrape TLDs from websites using Selenium')
    parser.add_argument('--input', required=True, help='Input file containing URLs (one per line)')
    return parser.parse_args()

def main():
    # Parse command line arguments
    args = parse_arguments()
    
    print("Starting TLD Scraper...")
    print(f"Input file: {args.input}")
    
    # Read input URLs (automatically skips comments and empty lines)
    urls_to_scrape = read_urls_from_file(args.input)
    if not urls_to_scrape:
        print("No valid URLs found to scrape. Exiting.")
        return
    
    print(f"Found {len(urls_to_scrape)} URLs to process")
    
    # Setup driver
    driver = setup_driver()
    all_tlds = set()
    
    try:
        for i, url in enumerate(urls_to_scrape, 1):
            print(f"Processing {i}/{len(urls_to_scrape)}: {url}")
            
            # Scrape URLs from current website
            found_urls = scrape_urls_from_website(driver, url)
            
            # Extract TLDs from found URLs
            for found_url in found_urls:
                tld = extract_tld_from_url(found_url)
                if tld:
                    all_tlds.add(tld)
            
            print(f"  Found {len(found_urls)} URLs, total unique TLDs: {len(all_tlds)}")
            
    except KeyboardInterrupt:
        print("\nProcess interrupted by user")
    finally:
        # Always close the driver
        driver.quit()
        print("WebDriver closed")
    
    # Save results in hosts file format to the specified directory
    if all_tlds:
        output_filename = os.path.join(
            "categories", 
            "porn", 
            datetime.datetime.now().strftime("%Y%m%d_%H%M%S") + "_hosts.txt"
        )
        
        if save_tlds_to_file(all_tlds, output_filename, args.input, len(urls_to_scrape)):
            print(f"Process completed! Found {len(all_tlds)} unique TLDs")
            print(f"Output file: {output_filename}")
            print(f"Total block entries in hosts file: {len(all_tlds)}")
            print(f"Directory: {os.path.dirname(output_filename)}")
        else:
            print("Error saving results")
    else:
        print("No TLDs found.")

if __name__ == "__main__":
    main()
